<?php
$ozeum_slider_sc = ozeum_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $ozeum_slider_sc ) && strpos( $ozeum_slider_sc, '[' ) !== false && strpos( $ozeum_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( ozeum_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$ozeum_anchor_icon = ozeum_get_theme_option( 'front_page_title_anchor_icon' );
		$ozeum_anchor_text = ozeum_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $ozeum_anchor_icon ) || ! empty( $ozeum_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $ozeum_anchor_icon ) ? ' icon="' . esc_attr( $ozeum_anchor_icon ) . '"' : '' )
									. ( ! empty( $ozeum_anchor_text ) ? ' title="' . esc_attr( $ozeum_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $ozeum_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$ozeum_scheme = ozeum_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $ozeum_scheme ) && ! ozeum_is_inherit( $ozeum_scheme ) ) {
			echo ' scheme_' . esc_attr( $ozeum_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( ozeum_get_theme_option( 'front_page_title_paddings' ) );
		if ( ozeum_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$ozeum_css      = '';
		$ozeum_bg_image = ozeum_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $ozeum_bg_image ) ) {
			$ozeum_css .= 'background-image: url(' . esc_url( ozeum_get_attachment_url( $ozeum_bg_image ) ) . ');';
		}
		if ( ! empty( $ozeum_css ) ) {
			echo ' style="' . esc_attr( $ozeum_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$ozeum_anchor_icon = ozeum_get_theme_option( 'front_page_title_anchor_icon' );
		$ozeum_anchor_text = ozeum_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $ozeum_anchor_icon ) || ! empty( $ozeum_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $ozeum_anchor_icon ) ? ' icon="' . esc_attr( $ozeum_anchor_icon ) . '"' : '' )
									. ( ! empty( $ozeum_anchor_text ) ? ' title="' . esc_attr( $ozeum_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( ozeum_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' ozeum-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$ozeum_css      = '';
			$ozeum_bg_mask  = ozeum_get_theme_option( 'front_page_title_bg_mask' );
			$ozeum_bg_color_type = ozeum_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $ozeum_bg_color_type ) {
				$ozeum_bg_color = ozeum_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $ozeum_bg_color_type ) {
				$ozeum_bg_color = ozeum_get_scheme_color( 'bg_color', $ozeum_scheme );
			} else {
				$ozeum_bg_color = '';
			}
			if ( ! empty( $ozeum_bg_color ) && $ozeum_bg_mask > 0 ) {
				$ozeum_css .= 'background-color: ' . esc_attr(
					1 == $ozeum_bg_mask ? $ozeum_bg_color : ozeum_hex2rgba( $ozeum_bg_color, $ozeum_bg_mask )
				) . ';';
			}
			if ( ! empty( $ozeum_css ) ) {
				echo ' style="' . esc_attr( $ozeum_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$ozeum_caption = ozeum_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $ozeum_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $ozeum_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $ozeum_caption, 'ozeum_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$ozeum_description = ozeum_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $ozeum_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $ozeum_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $ozeum_description ), 'ozeum_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( ozeum_get_theme_option( 'front_page_title_button1_link' ) != '' || ozeum_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						ozeum_show_layout( ozeum_customizer_partial_refresh_front_page_title_button1_link() );
						ozeum_show_layout( ozeum_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
